# Generated by Django 5.0.2 on 2024-03-18 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='Отсутствует')),
                ('dates', models.DateField(default=datetime.date.today)),
                ('info', models.TextField(default='Отсутствует')),
                ('FAQ', models.TextField(default='Отсутствует')),
                ('links', models.TextField(default='Отсутствует')),
            ],
        ),
    ]
