# Generated by Django 5.0.2 on 2024-07-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
