# Generated by Django 5.0.2 on 2024-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_info', models.TextField()),
                ('advises', models.TextField()),
                ('how_to', models.TextField()),
                ('FAQ', models.TextField()),
                ('treatment', models.TextField()),
                ('exclusion', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
    ]
