# Generated by Django 5.0.2 on 2024-03-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='short_title',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
