# Generated by Django 5.0.2 on 2024-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_information_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='short_title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
