# Generated by Django 5.0.2 on 2024-07-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_information_short_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='information',
            name='advises',
        ),
        migrations.RemoveField(
            model_name='information',
            name='boss_info',
        ),
        migrations.RemoveField(
            model_name='information',
            name='exclusion',
        ),
        migrations.RemoveField(
            model_name='information',
            name='history',
        ),
        migrations.RemoveField(
            model_name='information',
            name='how_to',
        ),
        migrations.RemoveField(
            model_name='information',
            name='treatment',
        ),
        migrations.AddField(
            model_name='information',
            name='info',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
