# Generated by Django 5.0.2 on 2024-07-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_remove_information_faq_remove_information_advises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='short_title',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
