# Generated by Django 5.0.2 on 2024-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('description', models.TextField(default='Отсутсвует')),
                ('structure', models.TextField(default='Отсутсвует')),
                ('work', models.TextField(default='Отсутсвует')),
                ('in_events', models.TextField(default='Отсутсвует')),
                ('FAQ', models.TextField(default='Отсутсвует')),
                ('links', models.TextField(default='Отсутсвует')),
            ],
        ),
    ]
