# Generated by Django 5.0.2 on 2024-03-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='links',
        ),
    ]
