# Generated by Django 5.0.2 on 2024-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_links_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
